force-app/main/default/objects/Resource__c.object
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Resource Preferences</relationshipLabel>
        <relationshipName>Resource_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource Preference</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MatchboxGetUserPreferences.cls
public with sharing class MatchboxGetUserPreferences {

    /**
     * Gets list of users current preferences for a list of resources. Primarily used in Flows.
     *
     * @param  List<List<Resource__c>> pResourceList        A list of resources to get current users preferences for
     * @return List<List<Resource_Preference__c>>           Returns the current list of user preferences
     */
    @InvocableMethod
    public static List<List<Resource_Preference__c>> getUserPreferences(
        List<List<Resource__c>> pResourceList
    ){

        Set<Id> resourceIdSet = new Set<Id>();

        for( Resource__c r_i : pResourceList[0] ){

            resourceIdSet.add( r_i.Id );
        }

        List<Resource_Preference__c> resourcePreferenceList = new List<Resource_Preference__c>([
            SELECT
                Id,
                Resource__c,
                Order__c
            FROM
                Resource_Preference__c
            WHERE
                    Resource__c IN :resourceIdSet
                AND OwnerId = :UserInfo.getUserId()
        ]);

        List<List<Resource_Preference__c>> rp = new List<List<Resource_Preference__c>>();
        rp.add( resourcePreferenceList );
        return rp;
    }
}