force-app/main/default/objects/Resource__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Slots__c</fullName>
        <label>Number of Slots</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Resource_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource Category</label>
        <referenceTo>Resource_Category__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Category__c.object
<CustomObject>
    <fields>
        <fullName>Diversity_Fields__c</fullName>
        <label>Diversity Fields</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>City</fullName>
                </value>
                <value>
                    <fullName>Department</fullName>
                </value>
                <value>
                    <fullName>Title</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resource_Collection__c</fullName>
        <label>Resource Collection</label>
        <referenceTo>Resource_Collection__c</referenceTo>
        <relationshipLabel>Resource Categories</relationshipLabel>
        <relationshipName>Resource_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Select_Preferred_Based_On_Diversity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Select Preferred Based On Diversity</label>
        <type>Checkbox</type>
    </fields>
    <label>Resource Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Collection__c.object
<CustomObject>
    <label>Resource Collection</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Matched__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Matched</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Resource Preferences</relationshipLabel>
        <relationshipName>Resource_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource Preference</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MatchboxGetUserPreferencesTest.cls
@IsTest
private class MatchboxGetUserPreferencesTest {
    
    /**
     * GIVEN: A collection, category, resources, user with preferences for resources
     * WHEN: Get user preferences is ran
     * THEN: Resources preferences are returned
     *
     * @return void
     */
    static testMethod void getUserPreferencesTest() {

        // Create a collection, cateogry with 2 resources
        Resource_Collection__c resourceCollection = new Resource_Collection__c(
            Name = 'Test Collection'
        );
        
        Database.insert( resourceCollection );
        
        Resource_Category__c resourceCategory = new Resource_Category__c(
            Name = 'Test Category',
            Resource_Collection__c = resourceCollection.Id,
            Diversity_Fields__c = 'City;Department;Title',
            Select_Preferred_Based_On_Diversity__c = true
        );
        
        Database.insert( resourceCategory );
        
        List<Resource__c> resourceList = new List<Resource__c>{
            new Resource__c(
                Name = 'Resource 1',
                Number_of_Slots__c = 2,
                Resource_Category__c = resourceCategory.Id
            ),
            new Resource__c(
                Name = 'Resource 2',
                Number_of_Slots__c = 2,
                Resource_Category__c = resourceCategory.Id
            )
        };
        
        Database.insert( resourceList );

        // Create a user with preferences for resources
        List<User> userList = new List<User>();
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];

        userList.add( 
            new User(
                Alias = 'standt',
                Email='standarduser@example.com', 
                EmailEncodingKey='UTF-8',
                LastName='Testing',
                LanguageLocaleKey='en_US', 
                LocaleSidKey='en_US',
                ProfileId = p.Id, 
                TimeZoneSidKey='America/Los_Angeles',
                UserName= (1)+'standarduser'+Math.random()+'@example.com'
            )
        );

        Database.insert( userList );

        List<Resource_Preference__c> resourcePreferenceList = new List<Resource_Preference__c>{
            new Resource_Preference__c(
                OwnerId = userList[0].Id,
                Resource__c = resourceList[0].Id,
                Order__c = 1,
                Matched__c = false
            ),
            new Resource_Preference__c(
                OwnerId = userList[0].Id,
                Resource__c = resourceList[1].Id,
                Order__c = 2,
                Matched__c = false
            )
        };

        Database.insert( resourcePreferenceList );

        List<List<Resource_Preference__c>> userResourcePreferences;

        // Get user preferences
        Test.startTest();

            System.runAs(userList[0]) {
                userResourcePreferences =  MatchboxGetUserPreferences.getUserPreferences(
                    new List<List<Resource__c>>{
                        resourceList
                    }
                );
            }
        
        Test.stopTest();

        // Assert we get the users resource preferences
        System.assertEquals(
            userResourcePreferences[0].size(),
            2
        );
    }
}